### ISSUE TITLE
console messages

### ISSUE THREAD

**Issue by justoverclockl** [askvortsov1/flarum-checklist#1]
is that normal?
![sdf](https://user-images.githubusercontent.com/79002016/134248308-133f7e09-2ac2-4d81-9007-7e61228bb904.png)

**Comment by askvortsov1** [comment]
Are you using the latest version of the extension? There's no console.logs in the current source code.

**Comment by justoverclockl** [comment]
yes, is 1.3.1 i think is related to davwheat PR for guestengagement.....console.log(itemlist)
